CREATE DATABASE unicommerce

CREATE TABLE `categoria` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(120) NOT NULL,
  `STATUS` tinyint NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `cliente` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(120) NOT NULL,
  `CPF` varchar(14) NOT NULL,
  `TELEFONE` varchar(14) DEFAULT NULL,
  `rua` varchar(120) NOT NULL,
  `numero` varchar(10) NOT NULL,
  `complemento` varchar(150) NOT NULL,
  `bairro` varchar(150) NOT NULL,
  `cidade` varchar(150) NOT NULL,
  `estado` char(2) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `pedido` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DATA` datetime NOT NULL,
  `CLIENTE_ID` int DEFAULT NULL,
  `DESCONTO` decimal(10,0) NOT NULL,
  `TIPO_DESCONTO` smallint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `CLIENTE_ID` FOREIGN KEY (`CLIENTE_ID`) REFERENCES `cliente` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `produto` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(200) NOT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  `PRECO` decimal,
  `QUANTIDADE_ESTOQUE` int DEFAULT NULL,
  `CATEGORIA_ID` int NOT NULL,
  PRIMARY KEY (`ID`,`CATEGORIA_ID`),
  CONSTRAINT `CATEGORIA_ID` FOREIGN KEY (`CATEGORIA_ID`) REFERENCES `categoria` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `item_pedido` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PRECO_UNITARIO` decimal(10,0) NOT NULL,
  `QUANTIDADE` int NOT NULL,
  `PEDIDO_ID` int NOT NULL,
  `PRODUTO_ID` int NOT NULL,
  `DESCONTO` decimal(10,0) NOT NULL,
 `TIPO_DESCONTO` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `PEDIDO_ID` FOREIGN KEY (`PEDIDO_ID`) REFERENCES `pedido` (`ID`),
  CONSTRAINT `PRODUTO_ID` FOREIGN KEY (`PRODUTO_ID`) REFERENCES `produto` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci